---
title: "Untitled"
output: html_document
date: "2024-11-08"
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
df=read_excel("sportsdata.xlsx")
```

Provided by Pro-Football-Reference.com: View Original Table
Generated 11/8/2024.

```{r cars}
view(df)
```

```{r}
colnames(df) <- c('NUM','Year','NumTeams','FGA0-19','FGM0-19','FGA20-29','FGM20-29','FGA30-39','FGM30-39','FGA40-49','FGM40-49','FGA50+','FGM50+','TFGA','TFGM','FGP','XPA','XPM','XPP')
```

```{r}
plotthing <- ggplot(data = df, aes(x=Year,y=`FGP50+`))+
  geom_point(aes(colour=`FGA50+`), stroke=1.1) + scale_y_continuous(labels = scales::percent) + geom_smooth(se = FALSE,linewidth = .7, color = "Red") + theme_classic() + 
  labs(x = "Year", 
    y = "Field Goal Convertion Rate Per Year",
    title ="Analysis of 50+ Yard Field Goals",
    subtitle = "Over the Last 44 Years",
    caption = "Data: Provided by Pro-Football-Reference.com,
                                Chart By Gabriel Rutherford 
                                            November 13th, 2024",
    colour = "FG Attempts Per Year")
```
```{r}
ggsave("project1g.png", plotthing, width = 12, 
       height = 7, units = "in")
```

```{r}
p <- ggplot(data = df, aes(x=Year, y=FGP)) + geom_col() + geom_smooth(se = FALSE, linewidth = 1.3) + theme_classic() 
p
```
```{r}
p <- ggplot(data = df, aes(x=Year, y=XPP)) + geom_col() + geom_smooth(se = FALSE, linewidth = 1.25) + theme_classic() 
p
```
```{r}
p <- ggplot(data = df, aes(x=Year, y=`FGP0-19`)) + geom_col() + geom_smooth(se = FALSE, linewidth = 1.25) + theme_classic()
p
```
```{r}
p <- ggplot(data = df, aes(x=Year, y=`FGM20-29`/`FGA20-29`)) + geom_col() + geom_smooth(se = FALSE, linewidth = 1.25) + theme_classic()
p
```

```{r}
p <- ggplot(data = df, aes(x=Year, y=`FGM30-39`/`FGA30-39`)) + geom_col() + geom_smooth(se = FALSE, linewidth = 1.25) + theme_classic()
p
```

```{r}
p <- ggplot(data = df, aes(x=Year, y=`FGM40-49`/`FGA40-49`)) + geom_col() + geom_smooth(se = FALSE, linewidth = 1.25) + theme_classic()
p
```
```{r}
p <- ggplot(data = df, aes(x = Year, y = `FGM50+`/`FGA50+`)) + geom_col() + geom_smooth(se = FALSE, linewidth = 1.25) + theme_classic()
p
```

```{r}
df <- mutate(df, `FGP0-19` = `FGM0-19`/`FGA0-19`, `FGP20-29` = `FGM20-29`/`FGA20-29`, `FGP30-39` = `FGM30-39`/`FGA30-39`, `FGP40-49` = `FGM40-49`/`FGA40-49`, `FGP50+` = `FGM50+`/`FGA50+`)
```

```{r}
view(df)
```


```{r}
library(shiny)
ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      selectInput("x", "Kick Statistic", 
                  c("Field Goal %" = "FGP", "Extra Point %" = "XPP",
                    "FG% Between 0-19 Yards" = "`FGP0-19`", "FG% Between 20-29 Yards" = "`FGP20-29`", 
                    "FG% Between 30-39 Yards" = "`FGP30-39`", "FG% Between 40-49" = "`FGP40-49`", 
                    "FG% 50+ Yards" = "`FGP50+`")),
      sliderInput("y", "Year Range", min = 1980, max = 2024, value = c(1980, 2024)),
    ),
    mainPanel(plotOutput(outputId = "Plot"))
  )
)
server <- function(input, output, session) {
  
  output$Plot <- renderPlot({
  df2 <- df[df$Year>=input$y[1]&df$Year<=input$y[2],]
    ggplot(data = df2, aes_string(x = df2$Year, y = input$x)) + geom_smooth(se = FALSE) +scale_y_continuous(labels = scales::percent)  + theme_classic() + labs(x = "Year", 
    y = "Field Goal Convertion Rate Per Year",
    title ="Analysis of NFL Kicking",
    subtitle = "Over the Last 44 Years",
    caption = "Data: Provided by Pro-Football-Reference.com,
                                Chart By Gabriel Rutherford 
                                            November 13th, 2024")
  })
}
shinyApp(ui = ui, server = server)
  
```

